kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-example
spec:
  selector:
    matchLabels:
      app: deployment-example
  template:
    metadata:
      labels:
        app: deployment-example
    spec:
      containers:
      - name: web
        image: openshift/deployment-example:v1
        ports:
        - containerPort: 8080
