kind: Pod
apiVersion: v1
metadata:
  name: hello-pod
  labels:
    name: hello-pod
spec:
  containers:
  - name: hello-pod
    image: bmeng/hello-openshift
    ports:
    - hostPort: 9500
      containerPort: 8080
