apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-rs
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  selector:
    matchLabels:
      app: example-rs
  template:
    metadata:
      labels:
        app: example-rs
    spec:
      containers:
      - name: example-rs
        image: app:v1
        ports:
        - containerPort: 8080
