apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-test-metrics-reader
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
