apiVersion: v1
kind: Build
metadata:
  name: ruby-hello-world-2
spec:
  strategy:
    sourceStrategy:
      env:
      - name: EXAMPLE
        value: sample-app
      from:
        kind: DockerImage
        name: docker.io/wewang58/ruby-22-centos7@sha256:fda21bc1af022fb34abbecb798a0cb1a37c82ef159b57df3e21688a6adcef9fa
    type: Source
